[package]
name = "diglyt-nock"
version = "0.0.0"
edition = "2018"

[dependencies]
byteorder = "1.3.1"
derive_more = "0.14.0"
env_logger = "0.6.1"
failure = "0.1.5"
lazy_static = "1.3.0"
log = "0.4.6"
lru-cache = "0.1.1"
serde = { version = "1.0.89", features = ["derive"] }
structopt = "0.2.15"
