#!/bin/bash
GIT_COMMITTER_DATE='Thu Jan  1 00:00:00 UTC 1970' \
GIT_COMMITTER_NAME='contributor' \
GIT_COMMITTER_EMAIL='\<\>' \
GIT_AUTHOR_DATE='Thu Jan  1 00:00:00 UTC 1970' \
GIT_AUTHOR_NAME='contributor' \
GIT_AUTHOR_EMAIL='\<\>' \
git commit --allow-empty-message "$@";
