merge_imports = true
use_field_init_shorthand = true
format_doc_comments = true
wrap_comments = true
indent_style = "Visual"
imports_layout = "Mixed"
use_small_heuristics = "Off"
fn_args_density = "Compressed"
comment_width = 92
max_width = 92
